//! PC glue binary: winit window + trino-platform-pc backend + example game.
//!
//! Assets are baked on startup from `assets/` into `target/assets/pc` and
//! loaded by stable handle. With `--features reload`:
//! - editing a master asset rebakes and re-uploads it live (same handle);
//! - editing game code rebuilds the dylib (via `cargo xtask watch pc`) and
//!   hot-lib-reloader swaps the functions under the running state.
//!
//! Env knobs:
//! - `TRINO_SMOKE_FRAMES=N` — exit cleanly after N frames (CI smoke tests).
//! - `TRINO_SIM=native|n64|3ds` — console simulation profile (default n64).

use std::path::PathBuf;
use std::sync::Arc;
use std::time::Instant;

#[cfg(not(feature = "reload"))]
use trino_core::Game;
use trino_core::{Input, Vec2};
use trino_platform_pc::{PcAudio, PcInput, PcRenderer, SimProfile};

use winit::application::ApplicationHandler;
use winit::dpi::LogicalSize;
use winit::event::{ElementState, KeyEvent, WindowEvent};
use winit::event_loop::{ActiveEventLoop, EventLoop};
use winit::keyboard::PhysicalKey;
use winit::window::{Window, WindowId};

#[cfg(feature = "reload")]
#[hot_lib_reloader::hot_module(
    dylib = "platformer",
    lib_dir = concat!(env!("CARGO_MANIFEST_DIR"), "/../../target/debug")
)]
mod hot_game {
    use platformer::PlatformerGame;
    use trino_core::{Audio, InputState, Renderer};

    // Exports generated by trino_game_api::export_game! in the game crate
    // (macro expansion is invisible to hot_functions_from_file!, so the
    // signatures are declared explicitly).
    #[hot_functions]
    extern "Rust" {
        pub fn trino_game_api_version() -> u32;
        pub fn trino_game_update(
            state: &mut PlatformerGame,
            input: &InputState,
            audio: &mut dyn Audio,
            dt: f32,
        );
        pub fn trino_game_render(state: &mut PlatformerGame, renderer: &mut dyn Renderer);
    }
}

fn assets_root() -> PathBuf {
    PathBuf::from("assets")
}

fn baked_dir() -> PathBuf {
    PathBuf::from("target/assets/pc")
}

struct Ctx {
    window: Arc<Window>,
    renderer: PcRenderer,
    audio: PcAudio,
    input: PcInput,
    game: platformer::PlatformerGame,
    last_frame: Instant,
    #[cfg(feature = "reload")]
    asset_events: std::sync::mpsc::Receiver<Vec<u32>>,
    #[cfg(feature = "reload")]
    _asset_watcher: Box<dyn std::any::Any>,
}

struct App {
    ctx: Option<Ctx>,
    profile: SimProfile,
    frames: u64,
    smoke_frames: Option<u64>,
}

/// Upload (or re-upload) baked assets by handle. Sounds are resampled to the
/// device rate at load time.
fn upload_assets(
    renderer: &mut PcRenderer,
    audio: &mut PcAudio,
    only: Option<&[u32]>,
) -> Result<(), String> {
    let assets = trino_asset_pipeline::load_dir(&baked_dir(), only)?;
    for sprite in assets.sprites {
        renderer.upload_sprite(
            trino_core::SpriteId(sprite.id),
            sprite.width,
            sprite.height,
            &sprite.rgba,
        );
    }
    for sound in assets.sounds {
        let samples = resample(&sound.samples, sound.sample_rate, audio.sample_rate());
        audio.upload_sound(trino_core::SoundId(sound.id), samples);
    }
    for track in assets.music {
        let samples = resample(&track.samples, track.sample_rate, audio.sample_rate());
        audio.upload_music(trino_core::MusicId(track.id), samples);
    }
    Ok(())
}

/// Linear-interpolation resampler — fine for short SFX in dev; the pipeline
/// gains proper resampling when music lands (Fase 6).
fn resample(samples: &[f32], from_rate: u32, to_rate: u32) -> Vec<f32> {
    if from_rate == to_rate || samples.is_empty() {
        return samples.to_vec();
    }
    let ratio = from_rate as f64 / to_rate as f64;
    let out_len = (samples.len() as f64 / ratio) as usize;
    (0..out_len)
        .map(|i| {
            let src = i as f64 * ratio;
            let idx = src as usize;
            let frac = (src - idx as f64) as f32;
            let a = samples[idx.min(samples.len() - 1)];
            let b = samples[(idx + 1).min(samples.len() - 1)];
            a + (b - a) * frac
        })
        .collect()
}

impl App {
    fn init(&mut self, event_loop: &ActiveEventLoop) -> Ctx {
        let attrs = Window::default_attributes()
            .with_title("Trino — platformer")
            .with_inner_size(LogicalSize::new(1280.0, 720.0));
        let window = Arc::new(
            event_loop
                .create_window(attrs)
                .expect("failed to create window"),
        );

        let mut renderer =
            pollster::block_on(PcRenderer::new_windowed(window.clone(), self.profile))
                .expect("failed to initialize wgpu renderer");
        let mut audio = PcAudio::new();

        // Bake + load. Dev-time convenience: the app always starts fresh.
        trino_asset_pipeline::bake_all(
            &assets_root(),
            trino_asset_pipeline::Platform::Pc,
            &baked_dir(),
        )
        .unwrap_or_else(|e| panic!("{e}"));
        upload_assets(&mut renderer, &mut audio, None).expect("failed to load baked assets");

        #[cfg(feature = "reload")]
        let (asset_events, watcher) = {
            let (tx, rx) = std::sync::mpsc::channel();
            let watcher = trino_asset_pipeline::watch::watch(
                assets_root(),
                trino_asset_pipeline::Platform::Pc,
                baked_dir(),
                move |changed| {
                    let _ = tx.send(changed);
                },
            )
            .expect("failed to start asset watcher");
            (rx, Box::new(watcher) as Box<dyn std::any::Any>)
        };

        let (iw, ih) = renderer.internal_size();
        let game = platformer::PlatformerGame::new(Vec2::new(iw as f32, ih as f32));

        window.request_redraw();
        Ctx {
            window,
            renderer,
            audio,
            input: PcInput::new(),
            game,
            last_frame: Instant::now(),
            #[cfg(feature = "reload")]
            asset_events,
            #[cfg(feature = "reload")]
            _asset_watcher: watcher,
        }
    }
}

impl ApplicationHandler for App {
    fn resumed(&mut self, event_loop: &ActiveEventLoop) {
        if self.ctx.is_none() {
            self.ctx = Some(self.init(event_loop));
        }
    }

    fn window_event(
        &mut self,
        event_loop: &ActiveEventLoop,
        _window_id: WindowId,
        event: WindowEvent,
    ) {
        let Some(ctx) = self.ctx.as_mut() else {
            return;
        };
        match event {
            WindowEvent::CloseRequested => event_loop.exit(),
            WindowEvent::Resized(size) => ctx.renderer.resize(size.width, size.height),
            WindowEvent::KeyboardInput {
                event:
                    KeyEvent {
                        physical_key: PhysicalKey::Code(code),
                        state,
                        repeat: false,
                        ..
                    },
                ..
            } => ctx.input.handle_key(code, state == ElementState::Pressed),
            WindowEvent::RedrawRequested => {
                // Live asset reload: swap content under stable handles.
                #[cfg(feature = "reload")]
                while let Ok(changed) = ctx.asset_events.try_recv() {
                    match upload_assets(&mut ctx.renderer, &mut ctx.audio, Some(&changed)) {
                        Ok(()) => println!("assets reloaded: {} item(s)", changed.len()),
                        Err(e) => eprintln!("asset reload failed: {e}"),
                    }
                }

                let now = Instant::now();
                // Clamp dt: debugger pauses and window drags must not
                // teleport the simulation.
                let dt = (now - ctx.last_frame).as_secs_f32().min(0.1);
                ctx.last_frame = now;

                let input = ctx.input.poll();

                #[cfg(feature = "reload")]
                {
                    let version = hot_game::trino_game_api_version();
                    assert_eq!(
                        version,
                        trino_game_api::GAME_API_VERSION,
                        "game dylib was built against a different game-api version — restart"
                    );
                    hot_game::trino_game_update(&mut ctx.game, &input, &mut ctx.audio, dt);
                    hot_game::trino_game_render(&mut ctx.game, &mut ctx.renderer);
                }
                #[cfg(not(feature = "reload"))]
                {
                    ctx.game.update(&input, &mut ctx.audio, dt);
                    ctx.game.render(&mut ctx.renderer);
                }

                self.frames += 1;
                if let Some(max) = self.smoke_frames
                    && self.frames >= max
                {
                    event_loop.exit();
                    return;
                }
                ctx.window.request_redraw();
            }
            _ => {}
        }
    }
}

fn main() {
    let smoke_frames = std::env::var("TRINO_SMOKE_FRAMES")
        .ok()
        .and_then(|v| v.parse().ok());
    let profile = std::env::var("TRINO_SIM")
        .ok()
        .and_then(|v| SimProfile::parse(&v))
        .unwrap_or(SimProfile::N64);

    let event_loop = EventLoop::new().expect("failed to create event loop");
    let mut app = App {
        ctx: None,
        profile,
        frames: 0,
        smoke_frames,
    };
    event_loop.run_app(&mut app).expect("event loop error");
}
