blank_issues_enabled: false
contact_links:
  - name: Question / discussion
    url: https://github.com/OWNER/trino/discussions
    about: Ask questions and discuss ideas in Discussions instead of issues.
